### ISSUE TITLE
the disconnect and connect options in the remote sub menu should be one single toggel option instead of 2 seperet options, read the discription.

### ISSUE THREAD

**Issue by amirmahdifard** [nvda-es/NVDARemote#14]
currently, we have 2 options in the remote sub menu, disconnect, and connect: when your remote is connected, the connect option in that menu will become disabled and unavailable to klick and the disconnect option will be enabled, and when your remote isn't connected, the disconnect option will become disabled and the connect option will be enabled: please make this option in to an only a single toggel option, wich acts and renames between disconnect, and, connect: when you are connected, this option will be disconnect, and, when your not connected, this option will be connect: in my opinion this way for  this option is a lot more modern and nice user interface, can you please do that if possible, i don't know how that's coded, but i feel it''s easy to do that: thank you!

**Comment by amirmahdifard** [comment]
@jmdaweb can you please say your opinion or implement this please, i also opened this in the nvda remote project, but they didn't pay any attention sadly: thanks so much if you did this.

**Comment by jmdaweb** [comment]
Hi,
This is not as easy as renaming the menu item, but can be achieved by removing and inserting items when needed. This is an excellent suggestion that improves add-on usability and prevents user confusion.
I have just uploaded a development release including this change. Please, test it and give feedback. If no issues are detected, this change will be included in the next stable release.
You can download the latest development version from this URL: https://nvda.es/files/get.php?file=tele-dev
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb you are greate! i just tested this will all possible bugs that it could create, and it didn't cause any problem! it exactly and greately works as how as i expected here, but there is something remanes: the shortcuts ("nvda+page+up") and ("nvda+page+down") for connect and disconnects are still same, what we are gonna do about them as whell, my suggestion is, to remove one of them, and make it like mute remote shortcut that it toggels between mute and unmute, we could have only a single shortcut for it, and say that when you are connected to remote, pressing this shortcut will disconnect you, and when you aren't connected, pressing this shortcut will bring up the connect dialog for you to connect: do you agree with my suggestion? if you agree, also do this with the shortcuts as whell, or if not and you only agree with option like this, then in my opinion, this is ready to be releaced publicly and stably: regards.

**Comment by amirmahdifard** [comment]
@jmdaweb also, please do an small change to the mute remote option
currently, if we are muted the remote, the option will appear as mute remote checked, if we are not muting the remote, it appears as just mute remote
please make it like this disconnect and connect option, it gets renamed instead of checked or not: so for example, if we are muted the remote, this option would appear as unmute remote, and when we are not muted it, it would appear as mute remote: this is also greate and nice user interface: thank you for doing this!

**Comment by amirmahdifard** [comment]
@jmdaweb hi again, this has a very little problem, wich i guess you got forgot to handle this part or something: when you are connected to the remote, and your connection gets interupted and reconnects again due to anything like your internet connection or anything, you will get 2 disconnect options in the remote sub menu: i guess it is because the addon is not being told to convurt this option also when your connection gets interupted, so this will be fixed if you do that, but there is no problem if we connect and disconnect manully: thanks.

**Comment by jmdaweb** [comment]
Hi,
Thanks. These were the kind of bugs I was expecting. After a shoft discussion with the community, they have decided that gestures won't be changed, but the proposal for the Mute remote option is also good.
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb hi, thanks, so if you want, please also do the change for the mute and unmute option and give another dev releace so we can try it, but probably it won't cause any problem anyway: then after that, it can be finally aplyed to the stable releace, wich i will be proud of it: thank you so much! i'll be waiting.

**Comment by amirmahdifard** [comment]
@jmdaweb about the bug that i've reported here, don't worry, that bug doesn't prevent user from working with the addon, you can be done with that bug so easyly: personally that bug doesn't stop my work: you can fix it if you know how to, or if you don't know, no worrys, that bug can stay for now, even in the stable releace.

**Comment by amirmahdifard** [comment]
@jmdaweb nice! i see you've fixed this bug too, then if you can, also do the mute thing too, then we can try that too! thanks for your hard work!

**Comment by jmdaweb** [comment]
Hi,
I will release a new dev version tomorrow with the mute option changed.
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb ok, thanks!

**Comment by amirmahdifard** [comment]
@jmdaweb i mean if you could give the developer version now it'd be greate, because i could test it with all possible things and give feedback untill to morro, as i'm excited about that: if no problem, could you give it now please?

**Comment by amirmahdifard** [comment]
@jmdaweb really nice! i got the new dev version a while ago and everything's working fine as expected, and after a bit i will try the connection interuption thing, i also tryed muting the remote and then disconnecting, and i tryed everything else, but there is no bug so far: really thanks for your work!

**Comment by jmdaweb** [comment]
In that case, this issue can be closed.
Thanks for your tests and your feedback!

**Comment by amirmahdifard** [comment]
@jmdaweb yes exactly, now i wanted to close this issue and wanted to tell you that this now can be proudly be included in to the stable releace because i just tryed the connection interupting several times, even i got my connection interupted when the remote is muted, and i'm happy and glad to tell you that i didn't face and didn't see any issue!, so this tikit is done with its job! really thank you for your developnent for this greate addon: i will come up with more cool suggestions!
