### ISSUE TITLE
please make the mute remote function to only work if you are on local computer, not in the remote computer

### ISSUE THREAD

**Issue by amirmahdifard** [nvda-es/NVDARemote#15]
i would need so if i'm muted the remote, it should be only muted if i'm on the local computer and i'm controling my own computer, but if i press f11 to go to the remote computer, i should here it and the mute function should stop work, because it makes no sence, if i muted the remote and i'm controling the remote computer, i can still controle it but i get no speech or anything, that's not really normal: also, doing this change would be a lot useful because sometimes i need to connect to a vps that more people are connected to it, and then i could mute the remote, so i won't get anything from the remote computer if i'm on my own local computer, and i will get speech and sounds again when i press f11 to controle the remote computer: thanks if you could see my point useful and do it please

**Comment by amirmahdifard** [comment]
@jmdaweb hi bro, can you see my point in this request, i was always looking for such a thing, even the same thing have been requested in the actual nvda remote project, but as normal, the developer of that project is sleeping L O L: thanks for your attention a lot!

**Comment by amirmahdifard** [comment]
@jmdaweb actually, it's a bug that when you muted the remote and press f11 to  work with the remote computer, you can still work with it but you don't know what you are doing because you have no speech, but this bug will be fixed if the mute only works when you are in the local computer: what you think? this addon is a greate addon, these suggestions even makes it more bettar and more wunderful! thanks!

**Comment by jmdaweb** [comment]
Hi,
Currently I control my personal and work computers at home from the same keyboard. One is next to the other, so I can mute the remote session and listen the speech and sounds directly from the remote computer without duplicating speech. I see your point, but I don't agree in this case.
You may assign a gesture to the mute function from the input gestures dialog. Then, if you want to stop hearing the remote computer, press f11 to return to local and quickly press that gesture. You can press the gesture again to unmute and f11 to control the remote computer. What do you think about that?
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb whell, i see your point, but what if you mute your remote computer's  speeckers and you lissen to your local computers speech? or, we can completely add a new option and call it mute only when in local computer? what do you think?

**Comment by amirmahdifard** [comment]
@jmdaweb actually yes i agree with you, i will use the shortcut raather than to make you add a new option for this: you can work on more good and useful things instead
