### ISSUE TITLE
bug: the dialog for the connection sicurity warning is not appearing and seems it's broken.

### ISSUE THREAD

**Issue by amirmahdifard** [nvda-es/NVDARemote#16]
hi
when i try to connect to untrusted remotes such as ttdr.ir or stuf like that, i should get the dialog and i should be able to press connect and don't ask for this server again, but the dialog is not appearing and it just says disconnected and i'm unable to connect: please fix this bug, and please also add an option to disable this connection sicurity warning system completely, personally i would insteantly disable that to be able to just connect to any server with out any confurmation and such, because i absolutely don't care about wether the server is safe or not or whatever, and i don't want to have it enabled: thank you.

**Comment by amirmahdifard** [comment]
@jmdaweb hi bro
can you please fix this, i had to swich to nvda remote for a little while because of this bug: thanks.

**Comment by jmdaweb** [comment]
Hi,
This has been fixed in version 2023.6.19.

**Comment by amirmahdifard** [comment]
@jmdaweb what about adding an option to disable this system?

**Comment by jmdaweb** [comment]
Hi,
I prefer leaving this system always activated. Imagine a person who performs a man in the middle attack. You believe that you are connected to a server, but you are connected to a malicious interceptor instead which steals your data or, in the worst case, takes control on your computer. Thanks to this dialog, you will notice that the server fingerprint has changed. It's better spending 10 seconds in a dialog than taking a serious privacy or security risk.
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb ok but i was just thinking what if someone wants to disable this system with their own responcability?

**Comment by jmdaweb** [comment]
Then, that user doesn't understand the risks of remote connections, and is not ready to control another machines in a secure way. In the other hand, if the user is expert and wants the dialog disabled, he will be able to modify the code himself.

**Comment by amirmahdifard** [comment]
@jmdaweb lol what if the person wants to do this but they don't know how to modify the code to disable this?

**Comment by Carlos-EstebanM** [comment]
Hi all.
A remote connection to another machine allows to a user have total control of a machine. For this reason, not is a good idea put an option to disable the security dialog in the user interface. Sometimes, a user probably disables important settings of security without understand completely what’s the consequences are. Additionally, if the user trust in a server, the dialog has a button for connect and don-t ask the question again.
Regards.
