### ISSUE TITLE
bettar user interface: when you are not connected to the remote, all options in the remote sub menu that are unavailable to klick should be completely disappear instead of being unavailable, and should appear when they are needed: please read the discription

### ISSUE THREAD

**Issue by amirmahdifard** [nvda-es/NVDARemote#19]
currently, when we are not connected to the remote, all options such as mute remote, send file, push klipboard, send controle alt delete coppy link,are unavailable to klick: these options should be removed and should be incerted when needed: so like this: when not connected, in the remote  sub menu only the connect, and options items should be there: when connected as allowed your computer to be controled, only push klipboard, send file, and coppy link items should be there: when connected as controle another computer, all items such as mute remote, send controle alt delete and everything should be inccerted and should be there: i would be so much happy if you also do this: i guess it is simple: just look at the code and remove and incert items instead of enabling and disabling them: thanks a lot!

**Comment by amirmahdifard** [comment]
@jmdaweb hi brother, if you could do this, i would be really happy and glad, it's a nice user interface and less confusing: because people can by mistake confuse or klick on disabled options: thanks!

**Comment by amirmahdifard** [comment]
@jmdaweb hi bro, please don't think i want to be annoying or something, just excited about this being aplyed: so, can you please say what you think and can you do this too, like the other suggestion i gave about the user interface and you did: thanks so much!

**Comment by amirmahdifard** [comment]
@jmdaweb hi, i know you mite be busy or something, but since a fue days ago i saw you doing some commits for the nvda remote server, just wanted to ask you could you do this one or what? thanks if you answer.

**Comment by amirmahdifard** [comment]
all contributers, inclooding @jmdaweb when i open an issue in any repo, after sometimes, i expect a comment or a disition that makes it clear that i should keep it open that i have a good suggestion and it will be implemented, or they tell me it can't be done for any reezen: then i can know it: i don't like to keep my issues open for too long and don't know what will happen to it: i just opened this here because i saw that you are interested to make this addon a bettar addon and acsept people's suggestions if they are good to add: thanks.

**Comment by jmdaweb** [comment]
Hi Amir,
I'm sorry, I have experienced issues with Github notifications these weeks. Another collaborator has just told me about your messages.
The suggestion, of course, is excellent. I'll leave the issue opened, although I haven't time enough to implement it myself. Other contributors may submit pull requests.
Hiding these options is not easy as showing / hiding the connect and disconnect options, because they are in first place in the menu and this makes the difference.
Best regards.

**Comment by amirmahdifard** [comment]
@jmdaweb ok then, thanks: i will keep this issue open until you get the time to implement this one, because i don't think others will even do that, because as faar as i see, only you were the one who worked at this project and other people didn't make even a single commit, or at least i didn't see any: i hope soon you get the time to work on this, and thanks.

**Comment by amirmahdifard** [comment]
@jmdaweb i understand you are busy, but please also consider implementing this sloly too, as i want to try it out and it would be a lot interesting interface if we don't have all options as unavailable, we only have the options that currently we can use them.

**Comment by amirmahdifard** [comment]
i wish someone could implement this at some point

**Comment by amirmahdifard** [comment]
@jmdaweb hi, you said you have github notification problems, so i hope you can see this commend, since i don't have your contact information: i juat want to ask you to do this, doing this will finish the work for the user interface of this addon, and would speed up our work a lot, since using this addon is ny interest a lot: thanks!

**Comment by amirmahdifard** [comment]
@jmdaweb hi bro, please really answer me if possible for you
bro, i have kept this issue for too long and i'm constantly checking for some news about it: can you do anything or take some time to implement this? i don't have much expectations from this addon, doing this would meat my expectation with user interface of this addon, since i have been using this addon instead of nvda remote addon for a long time now already:
please answer so i will know: thanks, a lot lot!

**Comment by amirmahdifard** [comment]
other contributers and colaborators, can you please let him know of my comment again so he can answer so i will know what to do before closing this or doing anything? thanks.

**Comment by jmdaweb** [comment]
guy, seriously you can be quite anoying. There are projects with long-standing issues which are opened for months or even years. Just wait and leave it open. It can be implemented via a pull request from a contributor, or from main developers when there is time enough to do it.

**Comment by bingen13** [comment]
I am not convinced this is a good UI change. It's bad to break user expectations, and there's a general expectation that menus are stable and have the same number of items. This way, once the user becomes proficient in the use of a given application, they can quickly scroll down the menu, knowing how many arrows to press. If the menu becomes unstable by the introduction and removal of items depending on the application state, this increases the cognitive load on a potentially distracted user. Bear in mind the failure mode of having a greyed out item is harmless, since all that happens is the item will not be activated. whereas the failure mode of pressing a given number of arrows and activating the wrong item as a result is larger.

**Comment by amirmahdifard** [comment]
@bingen13 hello, no, it's not about that, it's just that why disabled items should be there? disabled items could be removed because they are just useless anyway, since may be a user presses a disabled item rongly, because they would think that if the item is there, it means they can press it: and also, it speeds up advance users work because they don't have to scrole the disabled items as whell: and also, we don't memorise how many times we are pressing the arrow key because using a computer doesn't work like that: if i want to connect as an example, i don't care how many times i press my arow key, i will keep continue to press until i hear my nvda that says connect.

**Comment by jpavonabian** [comment]
@bingen13 is right. Although it would be a nice change for some users, there are cognitively impaired users who could be affected.
