### ISSUE TITLE
a gesture is needed for the send controle + alt + del option

### ISSUE THREAD

**Issue by amirmahdifard** [nvda-es/NVDARemote#27]
currently, we can only select the send controle + alt + del from the remote submenu, we cannot choos a gesture for it. this is needed for a quick work.

**Comment by amirmahdifard** [comment]
@jmdaweb if this idea is welcome to the project, please sighn me to this issue, i can do it.

**Comment by amirmahdifard** [comment]
for example, nvda+shift+controle+d can be used to send the controle alt del to the remote computer: i first opened an issue to make sure iam not waisting ny code

**Comment by jmdaweb** [comment]
OK, go ahead. Please, take the following into account:

* The script must be unassigned by default.
* The script must include category and description, so it can be assigned from the input gestures dialog.
* Include comments for translators in both the description and the spoken message when the gesture is pressed.
* Update the relevant section in the documentation.
* And, the last but the most important: be very careful with the spelling.

Awaiting for your pr to merge it.

**Comment by amirmahdifard** [comment]
@jmdaweb don't worry, i care about speling in my coding, speling eror only happens on my messages: and wich documentation? changelog, or readme? or both? and i was planning to a sighn nvda + controle + d, but ok, i will folow you

**Comment by jmdaweb** [comment]
Only documentation. I will take care of changelog, buildVars and the release process.

**Comment by ChrisDuffley** [comment]
> * Include comments for translators in both the description and the spoken message when the gesture is pressed.

For reference, this must be in the form of:
```
# Translators: Something like description/title of the gesture used to send Control+Alt+Delete to the remote machine.
```
Of course, something better than this, like exactly saying "The title of this gesture", etc. But you should at least have the idea.

Thanks, and @jmdaweb I'm very glad that you said to have this unassigned by default, as @amirmahdifard please keep in mind that NVDA+Control+D will open the Document Formatting panel in NVDA settings.

**Comment by amirmahdifard** [comment]
@ChrisDuffley thanks for your feedback:
1: yes, i know what to do with the translation comments, i was going to folow like the translator comments of other scripts, even if @jmdaweb didn't mention it to me because i know that it's needed.
2: yes i will leav it un assighned, but i meant to say nvda + controle + shift + d, not nvda + controle + d. Thanks.
