### ISSUE TITLE
an unassighned gesture to open the addon options dialog

### ISSUE THREAD

**Issue by amirmahdifard** [nvda-es/NVDARemote#29]
currently, we can assighne gestures... to open a specific catigory in the nvda settings dialog. it would be useful having an unassighned gesture for opening the tele nvda catigory in the nvda settings dialog, raather than always going to the menu and klicking the option.
@jmdaweb if you agree, please just leave a comment and i can do it. thanks. this is the last thing i think that is useful for this addon and i'm able to do it for now. thanks.

**Comment by jmdaweb** [comment]
Excellent idea. Go ahead.

**Comment by amirmahdifard** [comment]
done
