### ISSUE TITLE
Suggestion: Don't mute remote speech when controlling remote 

### ISSUE THREAD

**Issue by wmhn1872265132** [nvda-es/NVDARemote#32]
See
https://github.com/NVDARemote/NVDARemote/issues/282
I often need to remotely control other computers, but when I don’t control other computers, I don’t want to hear the voice output of other computers. Frequently switching remote mute is still a bit troublesome. In addition, when I need to control other computers, I often I forget to restore the remote computer's speech output, causing me to not hear the other computer's speech.
Thanks.

**Comment by amirmahdifard** [comment]
see the comments of https://github.com/nvda-es/TeleNVDA/issues/15

**Comment by amirmahdifard** [comment]
@jmdaweb since many users want this and requesting it and tele mvda is known to have a lot of useful features to meat the users expectations, and also to mot interupt the old way mute function, a checkbox should be added to the options dialog unchecked by default. When it is checked the mute function will not work when in the remote computer. Do you agree?

**Comment by jmdaweb** [comment]
Yes. It's time to implement this feature.

**Comment by amirmahdifard** [comment]
ok, so, will you do it, I actually have time to do it and am like to do it, but I don't know what I need to change in the mute function for this. please do it, or help me with your comment and i'm willing to do it for a quick implementation and help developers. Thanks.

**Comment by amirmahdifard** [comment]
i'll attempt to do this. I'll add a checkbox to the options dialog, called disable mute remote function when controling remote computer. When it is checked, calling the script to toggle between local and remote computer will also unmute when swiched to controle computer, and mute when swiched to local computer. @jmdaweb what do you say?

**Comment by jmdaweb** [comment]
Hi Amir,
I propose the following approach. Follow these steps to code the required changes:

* Add a checkbox labelled as "Mute remote speech when controlling local machine" (dialogs.py). Remember controlling the logic to retrieve and store the configured value. You can copy and adapt from other boolean settings.
* Add the required specification on configuration.py.
* Then, on __init__.py, check this setting on the script_sendKeys function. If it is enabled and we are returning to local machine, mute the remote speech (only if it's unmuted). If we are going to the remote machine, unmute the remote speech.
* The speech shouldn't be unmuted in any case if the controller muted it explicitly, for example from remote menu or pressing the remote gesture.
* Update documentation and changelog.

If you need help, let me know. Good luck! I'll review your pull request as soon as you open it and I have time enough. I am quite busy these days.

**Comment by amirmahdifard** [comment]
@jmdaweb ok, i'll do it. I hope i will be useful.

**Comment by amirmahdifard** [comment]
@wmhn1872265132 hi, i have developed this ability. you may try it and see if it fits your need? thanks.

**Comment by wmhn1872265132** [comment]
Thank you very much for your work, how can I download the test package?

**Comment by amirmahdifard** [comment]
@wmhn1872265132 you can download it from the pull request that i've opened, or if you can't build, i can provide the file, or just wait until the pr gets merged

**Comment by amirmahdifard** [comment]
@wmhn1872265132 hello, you can download a test version from here and try it. I'll attach it to this comment. Note. i'll upload a zip version because github doesn't support nvda-addon file extention, just download this file and rename its end to .nvda-addon instead of .zip, and then you can install it on your nvda and test it. 
[TeleNVDA.zip](https://github.com/nvda-es/TeleNVDA/files/13949595/TeleNVDA.zip)

**Comment by jmdaweb** [comment]
I'll perform some tests and close this issue as soon as they are completed.

**Comment by amirmahdifard** [comment]
ok, but i have tested all possible cases, and if you don't wish the announcement, i can disable it. Thanks for acsepting my work!

**Comment by wmhn1872265132** [comment]
Thanks for the work, this fits my needs, but the tip about muting might be better placed after the prompt for controlling the computer

**Comment by amirmahdifard** [comment]
@wmhn1872265132 ok, i'll just disable that.

**Comment by amirmahdifard** [comment]
@wmhn1872265132 hi, i'll upload a new build here, this should fix your issue about the muting and unmuting tips. Let me know if you have any other problems.
[TeleNVDA.zip](https://github.com/nvda-es/TeleNVDA/files/13960731/TeleNVDA.zip)

**Comment by amirmahdifard** [comment]
@wmhn1872265132 hi, i'll upload a new build here, this should fix your issue about the muting and unmuting tips. Let me know if you have any other problems.
[TeleNVDA.zip](https://github.com/nvda-es/TeleNVDA/files/13960772/TeleNVDA.zip)

**Comment by wmhn1872265132** [comment]
This version is very good, thanks again for your work

**Comment by amirmahdifard** [comment]
@wmhn1872265132 no problem, i'm happy that i could help you. Please pray for me i have a lot of problems in my life that i need god to solv them for me. Thanks.

**Comment by jmdaweb** [comment]
Hi,
This issue is fixed in latest release. Feel free to open a new one if you feel something is wrong. Thanks for the suggestion, the collaboration and the feedback.
Regards.
