### ISSUE TITLE
Allows NVDARemote users to also use TeleNVDA's protocol

### ISSUE THREAD

**Issue by cary-rowen** [nvda-es/NVDARemote#8]
Hello, I noticed that the protocol of the remote connection has been changed to 'teleNVDA://', but this will prevent users using NVDARemote from using the convenient remote connection. Do you have any thoughts on this?

I know that teleNVDA can handle the 'nvdaremote://' link protocol, however, NVDA Remote cannot handle the teleNVDA protocol. This is my main concern.
Can we make NVDARemote add-on compatible with 'TeleNVDA' protocol?
Or, I'd actually prefer TeleNVDA to use the more general 'NVDARemote' protocol.

**Comment by jmdaweb** [comment]
Hi,
A new submenu will be added in next versions, allowing to copy the link for NVDARemote or TeleNVDA.
Regards.

**Comment by cary-rowen** [comment]
For experienced people, it may not matter which protocol link is used, and it may even be possible to manually edit the link that has been copied to.
However, for novices, they probably don't know which protocol to choose.
I really don't think using the original 'nvdaRemote' protocol would defeat TeleNVDA's goals, or make TeleNVDA lose itself, it's still great.
That being the case, why not give users a better experience?

**Comment by jmdaweb** [comment]
I agree, but I don't still see switching to nvdaremote:// protocol as a good idea. Thush, I propose the following: adding a sub-menu to copy links with two options, NVDA Remote protocol and TeleNVDA. The first one would be the default and recommended in the documentation until there are significant differences in protocols, if it happens in the future. What do you think?

**Comment by cary-rowen** [comment]
I honestly don't see any benefit of using the 'teleNVDA' protocol, instead it would create confusion between users using both add-ons.
