### ISSUE TITLE
Explain in the documentation that transferring files will consume server traffic

### ISSUE THREAD

**Issue by cary-rowen** [nvda-es/NVDARemote#9]
TeleNVDA allows users to transfer files during remote assistance, which will undoubtedly consume the traffic of the relay server.
Some servers have limited traffic, this can be almost ignored if only text messages are being transferred, currently we can transfer files, I'm honestly worried about that.
Besides mentioning this in the docs, I would also like to know if, as NVDARemoteServer, there is a way to allow the administrator to freely switch the file transfer function.

@tech10 
Any ideas?

**Comment by jmdaweb** [comment]
Hi,
The server may have a new parameter to drop messages longer that a specified length. I wouldn't like to allow or deny specific types of messages, and keep the remote server as simple as possible. It was initially made for NVDA Remote, but it can relay almost everything, provided that the clients send messages in json format after joining a channel. Can you open an issue in the [NVDA Remote Server repository](https://github.com/jmdaweb/NVDARemoteServer)?
Thanks.

**Comment by tech10** [comment]
@cary-rowen For the official NVDA Remote Server, there is no way for an administrator to switch on or off the file transfer functionality. Unofficially, the specific type for file transfers could be blocked to prevent this, I believe it would be the file_transfer type in the JSON protocol. I'd be hesitant to do this myself since this is a forked version of the NVDA Remote add-on, but it might be a good idea to implement this somehow in the server run by this add-on, should someone not want to allow any file transfers on their server.

**Comment by cary-rowen** [comment]
yes, can you please implement this in go version of NVDARemoteServer, can there be a parameter to control whether to allow file transfer or not.
That way, it would be nice if the TeleNVDA Add-on would also know about this, and set the availability status of the menu item for teleporting files accordingly.

**Comment by tech10** [comment]
There's currently no way for TeleNVDA to set the menu item for sending files, based on a response it receives from a server, as far as I'm aware, the maintainers can correct me if I'm wrong. Such a response could be implemented in TeleNVDA, but the default would have to be enabled if backward compatibility with NVDARemote is to be maintained as it currently is, and allow the sending of files. The TeleNVDA add-on would have to be updated accordingly with the documentation changed, if necessary.

If this is updated in the future, I'll consider placing this functionality in the server I maintain in Go. For now, I can't implement this as you suggest until the TeleNVDA add-on is appropriately updated, if it ever is.

**Comment by jmdaweb** [comment]
Note that disabling file transfers won't prevent users to consume too much traffic if they want. The file transfer feature is inspired by the push clipboard option, which can be used to transfer large amounts of data, as well as the speech synthesizer under certain circunstances.

**Comment by cary-rowen** [comment]
Hello @tech10 
Sorry for commenting on a Closed Issue.
I saw that @jmdaweb pushed a commit related to this Issue, will you follow up?

https://github.com/jmdaweb/NVDARemoteServer/commit/75eed5d6a5b3068285a87f98432ad8ef06b85641

**Comment by tech10** [comment]
@cary-rowen 
Please open an issue on my repository for the NVDA Remote Server for what you're looking for, and I'll be happy to discuss it further there.
